### ISSUE TITLE
requests from pending request queue rejected immediately when system too busy

### ISSUE THREAD

**Issue by tjanczuk** [tjanczuk/iisnode#108]
When all available node.exe processes reached the quota of active requests, a request popped from the CPendingRequestQueue will be rejected with a 503 status code. Instead, the request should go back to the pending request queue. The fix must be done in CNodeProcessManager::TryDispatchOneRequestImpl.

**Comment by VinayParasrampuria** [comment]
There is queueLength setting on application pool which is set to default to 1000. However, it is not working as I would expect. If, for example, I set the nodeProcessCountPerApplication="1" and maxConcurrentRequestsPerProcess="1", I get a 503 for any second pending request. With the default queueLength, I would expect to get the service unavailable response on the 1001th pending request.

I am trying yo ensure IIS queue all the request instead of sending 503 and 503 should sent only for 1001th request. I am not sure where to configure this setting
