### ISSUE TITLE
setupsamples.bat fails to add or remove 'Default Web Site' root site.

### ISSUE THREAD

**Issue by shellscape** [tjanczuk/iisnode#269]
The setupsamples.bat throws errors when trying to find the Default Web Site even if it exists. It also cannot create 'Default Web Site' before trying to add the 'node' app to it. 

Environment:
Windows 8, x64.

**Comment by SteveyPugs** [comment]
I am having this issue as well.

```
C:\Program Files\iisnode>setupsamples.bat
Installation of node.js samples for IIS 7
This script must be run with administrative privileges.
This installer will perform the following tasks:
* ensure that the IIS_IUSRS group has read and write rights to "C:\Program Files\iisnode\www"
* delete the "Default Web Site/node" web application if it exists
* add a new site "Default Web Site/node" to IIS with physical path pointing to "C:\Program Files\iis
node\www"
This script does not provide means to revert these actions. If something fails in the middle you are
 on your own.
Press ENTER to continue or Ctrl-C to terminate.
Press any key to continue . . .
Ensuring IIS_IUSRS group has full permissions for "C:\Program Files\iisnode\www"...
processed file: C:\Program Files\iisnode\www
Successfully processed 1 files; Failed processing 0 files
...success
Ensuring the "Default Web Site/node" is removed if it exists...
ERROR ( message:Cannot find APP object with identifier "Default Web Site/node". )
Installation failed. Cannot ensure site "Default Web Site/node" is removed
```

**Comment by d2lam** [comment]
Same here. Anyone knows how to fix this?

**Comment by rramachand21** [comment]
What version of iisnode are you using? What version of windows are you running the script on?

**Comment by jwdavistx** [comment]
Having the same issue as mentioned above.

WIndows Server 2012 R2 x64
node v4.1.0
iisnode v0.2.11
IIS v8.5.9600.16384

**Comment by balasivagnanam** [comment]
+1 same error.. windows server 2012 R2 x64, node 4.2.2, iisnode v0.2.18 ,IIS 8

**Comment by Siyfion** [comment]
Also getting this issue; has anyone managed to solve this as-yet?

**Comment by jwdavistx** [comment]
A small update, but this is more from memory as it's been a few months since I touched this, but from what I remember my issue was that the script was looking for

"Default Web Site" but failing out if it didn't find it, as others are discovering.

I believe my issue was that what I actually had in IIS was "DefaultWebSite" vs "Default Web Site" so after making this change the script was able to deploy.

I ran in to more issues after that, but from what I remember it was ultimately a naming thing related to the actual site name in IIS vs what the script was looking for.

**Comment by Siyfion** [comment]
@jwdavistx Without sounding stupid, was your IIS install "fresh"? I mean, did you have any other existing websites running on your IIS instance (as I do), before wanting to add an additional node server.

**Comment by jwdavistx** [comment]
Pretty sure it was fresh, but I can't remember.  And there may have been some other minor tweaks, but from what I recall there was some kind of naming mismatch that was at least part of the issue I was having with setupsamples.bat

**Comment by xtawfnhdx** [comment]
@tjanczuk @jwdavistx @shellscape  the problem is OK?what solution？thx

**Comment by felixgondwe** [comment]
Late to the party but I got it to work on my machine. 
-----
Server 2012 R2 x64
node v6.0.0 (installed via nvm)
iisnode v0.2.21 x64
IIS v8.5.*
-----
In my case, I was getting similar error because I was missing "Default Web Site" in IIS. Followed the  following steps:
1. Create site called "Default Web Site"
2. Point the site to *\inetpub\wwwroot (some people don't like that but its okay)
3. Set application pool to "DefaultAppPool"
4. Restart CMD as admin(not sure if it matters but did it anyhow)
5. Navigate to *\iisnode and run setupsamples.bat
6. Open browser and navigate to http://localhost/node. It worked.

**Comment by derekbaker1986** [comment]
Thanks, @felixgondwe, You saved me a bunch of time. I'm new to .NET and IIS, and the SysAdmin is OOO, so I don't know how much time I would have spent on this. Better late than never.

**Comment by armanfatahi** [comment]
Thanks @felixgondwe . Step 3 and 4 was no needed in my case.

**Comment by alternapop** [comment]
I got this error as well. My Default Web Site was pointing to a folder on the D: drive and the app pool "Default Web Site". I changed the directory location to \inetpub\wwwroot  and the app pool to "DefaultAppPool" and it worked.

I then was able to change the site's folder back to the original D: drive location afterwards and it seems to still work.

Not sure why this is marked as 'closed' when the issue still persist.

**Comment by mkanavakatini** [comment]
Many thanks @felixgondwe and @alternapop. In my case, I also needed to add the original `http` binding back to have the host name `localhost`. Obviously the set up assumes you have freshly installed IIS and works off the boilerplate setup. Would be good if the script could be modified to allow for `Default Web Site` to be added, in the event that it does not exist.
