### ISSUE TITLE
Broken under Load

### ISSUE THREAD

**Issue by martinza78** [tjanczuk/iisnode#456]
We have a fairly complex node app running under webapps on azure and iisnode. We've been consistently getting random 500.1013's from it since we started especially under load. I've debugged, followed the EWT process, logging and couldn't track it down. The suggested response is that the errors are from uncaught exceptions.

Eventually I took the same repo, deployed on exactly the same size Linux VM and reran all the tests that were causing the 500's. ZERO errors and higher throughput.

In a production node environment, I suggest binning iisnode and web apps all together and running a linux environment.

**Comment by rramachand21** [comment]
How much load are you talking about?

**Comment by rramachand21** [comment]
500.1013 means that your node.exe is crashing because your app is throwing an exception.

**Comment by rramachand21** [comment]
Also, what is your azure webapp name? (you can private message me your azure webapp name so I can investigate).

**Comment by martinza78** [comment]
About 5k requests a minute. But it's irrelevant since the tests duplicate the same load in both environments, one throws errors, one doesn't. An exception from my app is also not true, same tests, same environment 0 exceptions from my app. Also I added immense amounts of logging to catch exceptions there and is nothing.

**Comment by martinza78** [comment]
How do i private message you?

**Comment by rramachand21** [comment]
rramachandra <at> live <dot> com

**Comment by rramachand21** [comment]
how many workers do you have? and what size did you select?

**Comment by rramachand21** [comment]
Comparing Linux VM with Windows Azure Websites VM is not a fair comparison. By default your content on azure websites is in a storage (shared across your workers) which is different from your linux vm (local disk content). In case of linux vm, you dont have the overhead of iisnode -- you lose the benefits of IIS like mentioned here http://tomasz.janczuk.org/2011/08/hosting-nodejs-applications-in-iis-on.html.. That said, depending on your application, there are options to optimize your application and configuration on azure websites. Like for example using Local Cache so your content is served from local cached copy instead of the storage.

**Comment by rramachand21** [comment]
Btw, You should set an appsetting on your site called NODE_PENDING_PIPE_INSTANCES to lets say 5000 .. This is to increase node.exe's max concurrent requests. By default node.exe allows only 4 concurrent requests (over named pipes). Please retry your tests after setting this setting.

**Comment by rramachand21** [comment]
Are you azure onPrem or azure websites  -- My comment about local disk vs storage applies only to azure websites (not the onPrem ofcourse).

**Comment by martinza78** [comment]
I'll retry it after that setting to see if it makes a difference. 

We're on Azure Websites. We'd prefer to run on webapps/websites for this, it does offer advantages but random 500's are causing a problem. And it's not exceptions in our code. It means it's difficult to track down.

Also, the info on the web is light. I followed well defined steps to get it running on linux. There's no information about running nodejs websites in production. No mention of the settings etc.

**Comment by rramachand21** [comment]
Just noticed, you are running on a 1 core VM -- You are running into memory issues and your w3wp + node.exe will get killed when you use 100% system memory (your app has about ~450MB memory available on a 1 core VM, if you exceed this, your processes will get killed and you will see the 503's you are seeing) -- You would need to scale up to prevent this.

**Comment by markusahlstrand** [comment]
We've been running into the same issues on multiple sites. We can't see the failing requests in the streaming logs or in new relic. Increasing the number of instances seems to work as a temporary fix but it would be great to track down the root cause. 
One question about the NODE_PENDING_PIPE_INSTANCES: Does app services by default only process 4 requests in parallell?

**Comment by rramachand21** [comment]
NODE_PENDING_PIPE_INSTANCES: is a node.exe setting -- its not related to app services or azure -- By default Node.exe has a max concurrent requests of 4 when using named pipes -- Since iisnode uses named pipe to communicate with node.exe, this setting applies to iisnode applications.. In the latest version of iisnode, I set the NODE_PENDING_PIPE_INSTANCES environment variable to a 50 when launching node.exe.. applications can override this value as well.

**Comment by markusahlstrand** [comment]
I got a bit confused by the info I got from support "You can increase the queue on node.exe using NODE_PENDING_PIPE_INSTANCES(default is 4), set this to 1000.", which I interpreted as that it just increased the length of the queue. But if I understand you correctly it sets the amount of concurrent requests being processed by node? If so, it's probably the root cause I hoped to find.

**Comment by rramachand21** [comment]
Yes, its the concurrent requests.

**Comment by rramachand21** [comment]
Its not a queue..

**Comment by markusahlstrand** [comment]
Great, thanks!

**Comment by martinza78** [comment]
I understand this is an artificial situation with the machine being put under pressure but it was done on purpose to reproduce the error. There's no exceptions for it except the 500.1013 deep in the websvc logs that doesn't say anything about memory problems, server too busy, node running out of connections etc. It's just a random 500 under load. which may be fine for a website where you can lose a request every now and again but for critical API's bound by SLA it's just not workable.

**Comment by rramachand21** [comment]
I looked at your VM and found the memory issues. The random 500's under load is not actually random -- It is related to the memory of your app -- When the VM memory reaches close to 100%, the most idle w3wp will be killed to free up memory which causes all the requests that were currently being processed by that w3wp to be killed and you will see 500's in this case.

**Comment by rramachand21** [comment]
Also, make sure to set the NODE_PENDING_PIPE_INSTANCES appsetting on your site to a high value like 5000 .. please see above for the details of this setting.

**Comment by NareshBanala** [comment]
I am getting 503 'iisnode was unable to establish named pipe connection to the node.exe process because the named pipe server is too busy' error intermittently.  Would I see this error because of NODE_PENDING_PIPE_INSTANCES settings?

**Comment by VinayParasrampuria** [comment]
Could you please confirm where and how  to set NODE_PENDING_PIPE_INSTANCES . A sample file will be great . I tried setting it up in webconfig along with node_env but it doesn't allow my node to start .

**Comment by rramachand21** [comment]
If you are using iisnode v0.2.21 and above, iisnode automatically sets NODE_PENDING_PIPE_INSTANCES to a high value of 5000. If you are using older versions of iisnode, you can set a system env variable NODE_PENDING_PIPE_INSTANCES to a high value.

**Comment by JogoShugh** [comment]
How do you know what version of IISNODE you're using?

**Comment by JogoShugh** [comment]
Nevermind, I figured that part out, and we are indeed running a high enough version such that the PENDING parameter is set very high:

![image](https://cloud.githubusercontent.com/assets/1863005/25355203/d411ec0e-2903-11e7-8a5b-fb9327df43a2.png)

**Comment by sheldonanto** [comment]
Hi guys,  I have the same issue while sending more than 230 MB  in the Request body 
(HTTP Error 500.1013 - Internal Server Error)
