### ISSUE TITLE
Load environment variable into config from external environment.

### ISSUE THREAD

**Issue by calebgregory** [tjanczuk/iisnode#482]
I'm deploying to Windows Server 2012 R2 using Octopus Deploy.  In Octopus Deploy, I can declare environment variables, for example `NODE_ENV`, for a given environment.

In the web.config, what seems to be required is a hard-coded declaration, e.g., 
```
<iisnode
    node_env="production"
/>

<!-- OR -->

<appSettings>
    <add key="NODE_ENV" value="production" />
</appSettings>
```

I'd like to grab this from my Octopus configuration, rather than having to manage two separate `web.config` files on, in this case, my `dev` branch and my `master` branch.  That way, (a.) there is a central location for holding this information and (b.) I won't have to resolve a merge conflict every time I merge to `master`, which will make life much easier for myself and whoever inherits this application in the future.  Is this possible and I'm missing the way, or if not, can it be?

**Comment by calebgregory** [comment]
I found a work around - setting a global environment variable on the server `NODE_ENV`, which I can pull into `web.config` with ```
<iisnode
    node_env="%NODE_ENV%"
/>
```

I'm still wondering if ^ what I'd like to do ^ is possible so I'm going to leave this open, but in the meantime I've found a way to do resolve my concerns stated above in (b.).

**Comment by rramachand21** [comment]
the only way to read this is from environment variables. I am not sure if Octopus can be configured to write to your web.config directly.

**Comment by reg0** [comment]
@calebgregory your posts are rather old, but I had exactly the same problem and I found a solution

as you probably know, you may put env vars in web.config file like that:

```
<appSettings>
    <add key="INSTANCE_NAME" value="staging" />
</appSettings>
```

but we don't want to check that into git, right? I found that you may load appSettings section from external source like that: `<appSettings configSource="appSettings.config">`

Now, what I did was to:
- create appSettings.config file with my env vars as above
- add it to gitignore so that I don't have problems with merging
- create a copy of it (appSettings.config.template) and CHECK IT IN

With that:
- I have a .template in the repository
- I can copy it in the deployable location, remove the suffix, adjust variables values for specific deployment
- I only modify a copy of the template, which is not tracked by git
