### ISSUE TITLE
Is iisnode dead?

### ISSUE THREAD

**Issue by MarkHerhold** [tjanczuk/iisnode#483]
I see a lot of (good) questions that are unanswered in the issues and it doesn't appear that there is active development on this project. Is this project dead?

**Comment by pbaio** [comment]
That's a good question. I know that it is actively used a good amount but, it seems like the new maintainer @rramachand21 seems to rarely respond to quality questions. I know that @tjanczuk isn't an active maintainer. I think it may be time that an IISNode alternative gets developed.

**Comment by tjanczuk** [comment]
Hi Mark, responded on GitHub.


Thanks,

Tomasz


________________________________

**Comment by Siafu** [comment]
I use this in a production application and I'll admit. I am worried about the future of the project.

**Comment by matterker** [comment]
@tjanczuk what did you mean by "responded on GitHub" in reply to Mark?
I too am curious about the long term viability of iisnode. (Though it has been working flawlessly for me for about two years.)
Thank you!

**Comment by tjanczuk** [comment]
@matterker I am sorry, my comment above was in relation to another issue, I replied to the wrong e-mail notification from Github. 

I have left the iisnode project in the caring hands of Microsoft when I left the company in 2013, and I have not been actively maintaining it since. You may see me dropping a comment here or there but this is not to mean I am actively engaged. 

As much as I am not in a position to comment on Microsoft plans regarding iisnode, I do observe the iisnode project is still a necessary component that enables Windows Azure Websites to run Node.js applications, just as it was back in 2013. I would be surprised if it were going away any time soon, at least without a viable alternative or path forward to ensure apps running on top of it continue to function.

**Comment by rramachand21** [comment]
@pbaio - I am not just working on iisnode - I am actively working on Microsoft Azure Webapps features that need my attention. If you have any critical questions about iisnode, please mail me. 
Or else, Please wait for me to get through and sort out the issues and determine which ones are "Quality" questions or not.

**Comment by devotis** [comment]
Is there anybody with the authorization to close issues actively monitoring here on Github? IIsnode is important for many production systems. Open Issues piling up, doesn't contribute to a sustainable future for iisnode in the long term.

**Comment by rramachand21** [comment]
Hi All, I work on iisnode part time. Please let me know what issues you think are important and I will try to work on them. Btw, iisnode is open source so please do start contributing fixes and features if needed.

**Comment by queequac** [comment]
@rramachand21 The projekt being open source does not help if feature requests including PR are ignored. Just have a look at #381; a lot of People support (or in some cases really need) this feature - even you yourself said it was a good idea in the first place.

The current situation leads to a fragmentation of forks, none of them getting any attention while the master repo here is in Snow White's sleep.

Btw, if feature request as the one mentioned one above are definitely not considered, someone should at least close them. That's another point @devotis was referring to in his comment.

**Comment by rramachand21** [comment]
@queequac, just FYI, #381 will be included by end of this month. The PR submitted needs some modifications (like instead of using numbers in the cookie, I would want a guid associated with the process).

**Comment by queequac** [comment]
@rramachand21 Mid of December in the meanwhile... did the modified PR already land? ,-)

**Comment by franklinyu** [comment]
I have switched to https://github.com/Azure/iisnode which is actively maintained.
