### ISSUE TITLE
iisnode encountered an error when processing the request.

### ISSUE THREAD

**Issue by sanjuljain05** [tjanczuk/iisnode#510]
I have created a node js application, which scans the input from a serial port device and sends it to the browser, for which I have created a HTML page. The application is deployed on IIS using iisnode, however when I try to open the page in browser it gives an 
HRESULT: 0x2
HTTP status: 500
HTTP subStatus: 1001
HTTP reason: Internal Server Error

I have assigned full control permissions to the identity running the application,but it still did not work. 
The ETW gives the following message :-
iisnode leaves CNodeHttpModule::OnAsyncCompletion with RQ_NOTIFICATION_FINISH_REQUEST 
This is followed by
 iisnode scheduled a retry of a named pipe connection to the node.exe process.

I am fairly new to node js and IIS  and cant figure out , how to make it work. Below is my code for node js file:- 

var serialport = require("serialport");
var WebSocketServer = require('ws').Server;

var SERVER_PORT = 9000;               // port number for the webSocket server
var wss = new WebSocketServer({port: SERVER_PORT}); // the webSocket server
var connections = new Array;          // list of connections to the server

var SerialPort = serialport.SerialPort; // localize object constructor
serialport.list(function (err, ports) {
	  ports.forEach(function(port) {
		console.log(port.comName);
//var portName = "COM5";

var myPort = new SerialPort(port.comName, {
   baudRate: 9600,
   // look for return and newline at the end of each data packet:
  // parser: serialport.parsers.readline("\n")
   parser: serialport.parsers.raw
 });

Thank you for your help in advance.

**Comment by hoffmanic** [comment]
Hi there, I have been having the same errors (but for different reasons), my understanding of this error. Is that a communication with the nodejs process and issnode cannot be established within the retry limits of issnode.

I also note that you are using a fixed port for your application. you should change the code to use process.env.PORT || 9000 as iinode uses a named pipe instead of a port number and perhaps why the process is trowing a 500.1001.

Hope this helps.

**Comment by sanjuljain05** [comment]
Thanks for the reply, i did change the code for port also looks like I was missing some access on the server and now can view the page in browser.

**Comment by karun-r** [comment]
In my express app, I am using process.env.PORT || 3000 and I am able to browse the app when I run it from cmd line and listen on port 3000 but when I deploy it in IIS, I am getting the above error (HTTP 500). Any help here?

**Comment by mbrookson** [comment]
@karun-r Did you ever fix this issue? I am seeing the exact same issue.

I have given full permissions to all relevant folders and still no luck.

I have also run the EWT program and discovered the process seems to log this...

- iisnode received a new http request
- iisnode increases pending async operation count
- iisnode initialized a new node.exe process
- iisnode scheduled a retry of a named pipe connection to the node.exe process

...

- iisnode was unable to establish named pipe connection to the node.exe process before the process terminated

Trying to get an Angular Universal (SSR) app running in IIS

**Comment by karun-r** [comment]
@mbrookson I vaguely remember that the log on my server when I faced this issue was somewhat similar to the log that you've posted. Unfortunately, I could not figure out why this was happening and I ultimately built my site, which was some simple POC for another project, using .NET and deployed it on Azure. 

I had a pretty bad experience using iisnode back then. I never touched node js again when working with windows servers.

**Comment by arekade** [comment]
@mbrookson Did you manage to fix you issue?

**Comment by mbrookson** [comment]
@arekade I'm afraid not. It was quite a while ago so can't remember how far I got but decided to give up in the end unfortunately.
